name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache Yarn modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock) }}

    - name: Run build.sh
      run: |
        yarn run export:proxy

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: out/