name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache Yarn modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock) }}

    - name: Run build.sh
      run: |
        yarn run export:proxy

    - name: Login to DockerHub
      uses: docker/login-action@v3
      if: github.event_name == 'workflow_dispatch'
      with:
        registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.ALI_DOCKER_HUB_USN }}
        password: ${{ secrets.ALI_DOCKER_HUB_PWD }}

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      if: github.event_name == 'workflow_dispatch'
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/zhangjian10/chat-web:${{ steps.vars.outputs.sha_short }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: out/